"""Human-readable mining report (§12).

Produces reports/<dataset>/mining_report.md: dataset/split, sample sizes, feature
count, candidates tested, accepted/rejected counts, breakdown by rule type and
provenance, thresholds + tolerance policy, high-support rejected rules,
suspicious rules, and a full catalog of accepted rules with plain-English
explanations and evidence.
"""
from __future__ import annotations

from collections import Counter

import numpy as np

from validation.validator.rule import Rule


def _hist(support: list[float]) -> str:
    a = np.asarray(support, float)
    if a.size == 0:
        return "(no candidates)"
    edges = [0.0, 0.5, 0.9, 0.99, 0.999, 0.9999, 1.00001]
    labels = ["[0.00,0.50)", "[0.50,0.90)", "[0.90,0.99)", "[0.99,0.999)",
              "[0.999,0.9999)", "[0.9999,1.0]"]
    counts = np.histogram(a, bins=edges)[0]
    lines = ["| train-support bucket | #candidates |", "|---|---|"]
    for lab, c in zip(labels, counts):
        lines.append(f"| {lab} | {int(c)} |")
    return "\n".join(lines)


def _rule_block(r: Rule) -> str:
    ev = r.evidence
    ts = ev.get("train_support_full", ev.get("train_support"))
    vs = ev.get("validation_support_full", ev.get("validation_support"))
    te = ev.get("eligible_rows_train_full", ev.get("eligible_rows_train", "?"))
    tol = r.tolerance
    lines = [
        f"### {r.id}  ({r.rule_type})",
        "",
        f"- **Expression:** `{r.expression()}`",
        f"- **Source:** MINED",
        f"- **Interpretation:** {r.description}",
        f"- **Training support:** {ts:.6f}" if ts is not None else "- **Training support:** n/a",
        f"- **Validation support:** {vs:.6f}" if vs is not None else "- **Validation support:** n/a",
        f"- **Eligible rows (train):** {te:,}" if isinstance(te, int) else f"- **Eligible rows (train):** {te}",
        f"- **Tolerance:** absolute={tol.absolute:.3g}, relative={tol.relative:.3g}",
    ]
    if ev.get("abs_error"):
        ae = ev["abs_error"]
        lines.append(f"- **Train abs-error:** p50={ae['p50']:.3g} p99={ae['p99']:.3g} max={ae['max']:.3g}")
    lines.append(f"- **Decision:** ACCEPTED — {ev.get('why_accepted','high train+val support')}")
    lines.append("")
    return "\n".join(lines)


def build_mining_report(dataset, names, profile, families, fam_counts, n_candidates,
                        kept, pruned, rejected, support_hist, ext_rules, proto,
                        thr_train, thr_val, prefilter, tol_pct, elapsed) -> str:
    L: list[str] = []
    L.append(f"# Mining report — {dataset}")
    L.append("")
    L.append("Generated by `python -m validation.mining.run_mining`. All discovery is on the "
             "**train** split; every accepted rule is independently confirmed on the held-out "
             "**validation** split. The **test** split is never used for discovery, thresholds, "
             "or tolerance selection.")
    L.append("")
    L.append("## 1. Dataset & splits")
    L.append("")
    L.append(f"- Dataset: `{dataset}` (DistriNet-corrected CICFlowMeter, raw/pristine feature space)")
    L.append(f"- Features: **{len(names)}**")
    L.append("- Discovery split: **train** (1,456,265 rows; sampled for candidate scan, full for final support)")
    L.append("- Confirmation split: **validation** (312,058 rows)")
    L.append("- Test split: **not used** (leakage-guarded in `data_access.load_split`)")
    L.append(f"- Wall time: {elapsed:.1f}s")
    L.append("")
    L.append("## 2. Candidate grammar")
    L.append("")
    L.append(f"- Total candidate rules tested: **{n_candidates}**")
    for fam, c in fam_counts.items():
        L.append(f"  - {fam}: {c}")
    L.append("")
    L.append("Grammar families: pairwise (`A~=B`, `A<=B`, `A~=k*B`, `A~=B^2`), three-feature "
             "arithmetic (`A~=B+C`, `A~=B-C`, `A~=B*C`, `A~=B/C`), statistical ordering "
             "(`Min<=Mean<=Max`, `Var~=Std^2`), and zero-implications (`A==0 => B==0`). "
             "Constants for scaled relations are restricted to {2, 0.5, 10, 100, 1000, 1e6}; "
             "no arbitrary coefficients are fit (§5, §18).")
    L.append("")
    L.append("## 3. Thresholds & tolerance policy")
    L.append("")
    L.append(f"- Prefilter support (small train sample): >= {prefilter}")
    L.append(f"- Train support to accept: >= {thr_train}")
    L.append(f"- Validation support to accept: >= {thr_val}")
    L.append(f"- Approximate-rule tolerance: absolute = max(1e-6, p{tol_pct} of |train residual|), "
             f"capped; relative = p{tol_pct} of |residual|/(|expected|+1), capped at 0.10. "
             f"Logical rules (<=, chains, implications) use a fixed 1e-6 floor.")
    L.append(f"- Implications require antecedent rate >= 0.01 and >= 1000 eligible rows (§7).")
    L.append("")
    L.append("## 4. Candidate support distribution (train prefilter sample)")
    L.append("")
    L.append(_hist(support_hist))
    L.append("")
    L.append("## 5. Outcome summary")
    L.append("")
    L.append(f"- Accepted (before pruning): **{len(kept) + len(pruned)}**")
    L.append(f"- Retained after pruning: **{len(kept)}**")
    L.append(f"- Pruned (dominated/duplicate/extractor-covered): **{len(pruned)}**")
    L.append(f"- Rejected: **{len(rejected)}**")
    L.append("")
    by_type = Counter(r.rule_type for r in kept)
    L.append("Accepted rules by type:")
    for t, c in sorted(by_type.items()):
        L.append(f"  - {t}: {c}")
    L.append("")
    L.append("Provenance breakdown of the full validator (this run mines MINED only; "
             "SCHEMA/EXTRACTOR/PROTOCOL are profiles):")
    L.append(f"  - MINED (this run): {len(kept)}")
    L.append(f"  - EXTRACTOR (profile): {len(ext_rules)}")
    L.append(f"  - PROTOCOL (profile): {len(proto['rules'])}")
    L.append("")
    L.append("## 6. High-support rejected rules (inspect thresholds)")
    L.append("")
    hi = sorted([x for x in rejected if x.get("train_support", 0) >= 0.9],
                key=lambda x: -x.get("train_support", 0))[:40]
    if not hi:
        L.append("(none with train support >= 0.90)")
    else:
        L.append("| expression | type | train support | val support | reason |")
        L.append("|---|---|---|---|---|")
        for x in hi:
            r = x["rule"]
            L.append(f"| `{r.expression()}` | {r.rule_type} | {x.get('train_support',0):.5f} | "
                     f"{x.get('validation_support','-') if isinstance(x.get('validation_support'),str) else format(x.get('validation_support',0),'.5f')} | {x['reason']} |")
    L.append("")
    L.append("## 7. Pruned rules (with reason)")
    L.append("")
    if not pruned:
        L.append("(none)")
    else:
        L.append("| expression | type | why_pruned |")
        L.append("|---|---|---|")
        for r, why in pruned:
            L.append(f"| `{r.expression()}` | {r.rule_type} | {why} |")
    L.append("")
    L.append("## 8. Accepted MINED rules (full catalog)")
    L.append("")
    if not kept:
        L.append("(none)")
    for r in kept:
        L.append(_rule_block(r))
    return "\n".join(L)
